# Module
# https://gohugo.io/hugo-modules/configuration/
# https://www.thenewdynamic.com/article/hugo-modules-everything-from-imports-to-create/
# ################################
mounts:
  - source: layouts
    target: layouts
  - source: assets
    target: assets
  # Returning partials are core elements which should sit at the root of the project.
  - source: func
    target: layouts/partials/func
  # We'll keep the uploads dir at the root of the repo while mounting it underneath `assets/upload` to comply with HUGE/Media.
  # If HUGE/Media is used in conjunction with `imgix`, this could be mounted into static.
  # See https://github.com/theNewDynamic/huge/wiki/Media#settings-all
  - source: uploads
    target: assets/uploads
  # Huge's config is mounted in the assets directory
  - source: _huge
    target: assets/_huge
imports:
  - path: github.com/theNewDynamic/huge
  - path: github.com/theNewDynamic/hugo-module-tnd-forms
  - path: github.com/theNewDynamic/hugo-module-tnd-socials
  - path: github.com/theNewDynamic/hugo-module-tnd-menus
  - path: github.com/theNewDynamic/hugo-module-tnd-headers
  - path: github.com/theNewDynamic/hugo-module-tnd-redirects
  - path: github.com/theNewDynamic/hugo-module-tnd-search
  - path: github.com/theNewDynamic/hugo-module-tnd-icons
  - path: github.com/theNewDynamic/hugo-module-tnd-blocks
  # If we need iuebenda
  # - path: github.com/theNewDynamic/hugo-module-tnd-iubenda
