[build]
publish = "public"
command = "hugo -s _prebuild --cleanDestinationDir && hugo --minify"

[build.environment]
  GO_VERSION = "1.14"
  NODE_VERSION = "16.14.0"
  HUGO_VERSION = "0.107.0"
  TND_SITE_ID = "data-sandbox"

[context]

[context.production]

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -s _prebuild --cleanDestinationDir && hugo --minify -D -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_ENV = "staging"

[context.branch-deploy]
command = "hugo -s _prebuild --cleanDestinationDir && hugo --minify $DEPLOY_URL"
[context.branch-deploy.environment]
HUGO_ENV = "staging"

[dev]
  command = "hugo server -e development -F -D"
  functions = "functions"
  publish = "public"
  port = 8888
  targetPort = 1313
  framework = "#custom"